{{- range $env := .Values.satellite.environments }}
{{- if $env.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxysql-satellite-{{ $env.name }}-config
  labels:
    app: proxysql
    component: satellite
    environment: {{ $env.name }}
    {{- include "fli-proxysql.labels" $ | nindent 4 }}
data:
  proxysql.cnf: |
{{ $env.config | indent 4 }}
    proxysql_servers =
    (
{{- range $i := until (int $.Values.core.replicaCount) }}
      { hostname = "{{ $.Values.core.name }}-{{ $i }}.{{ $.Values.core.name }}", port = 6032, weight = 1000 }{{ if ne $i (sub (int $.Values.core.replicaCount) 1) }},{{ end }}
{{- end }}
    )

{{- end }}
{{- end }}
